import styles from '../styles/Home.module.scss'
import { Button, Form } from 'semantic-ui-react'
import Head from 'next/head'
import router from 'next/router'
import {useState} from 'react'

export default function Home() {

  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.title}>
          ZallpyChat <a href="#">Realtime!</a>
        </h1>

        <p className={styles.description}>
          Acesse o sistema por aqui:
        </p>
        <Form onSubmit={login}>
          <Form.Field>
            <label>Email</label>
            <input onChange={e => setEmail(e.target.value)} placeholder='Digite seu e-mail' type={"email"} />
          </Form.Field>
          <Form.Field>
            <label>Senha</label>
            <input onChange={e => setPassword(e.target.value)} placeholder='Digite sua senha' type={"password"} />
          </Form.Field>
          <Button  primary className={styles.buttonPrimary} type={'submit'}>Entrar</Button>
        </Form> 
        </main>
         {modal}
    </div>
  )
}

