import styles from '../styles/Login.module.scss'
import { Button, Form, Modal } from 'semantic-ui-react'
import Head from 'next/head'
import {useState} from 'react'
import router from 'next/router'
import {auth} from '../firebase'
import { signInWithEmailAndPassword } from "firebase/auth";

export default function Home() {

  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")
  const [mensagem, setMensagem] = useState("")
  
  function login(){
    signInWithEmailAndPassword(auth, email, password)
    .then((userCredential) => {
      const user = userCredential.user;
      console.log(user)
      router.push('/home')
    })
    .catch((error) => {
      setMensagem(error.message);
    });
      
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.title}>
          ZallpyChat <a href="#">Realtime!</a>
        </h1>

        <p className={styles.description}>
          Acesse o sistema por aqui:
        </p>
        <Form onSubmit={login}>
          <Form.Field>
            <label>Email</label>
            <input onChange={e => setEmail(e.target.value)} placeholder='Digite seu e-mail' type={"email"} />
          </Form.Field>
          <Form.Field>
            <label>Senha</label>
            <input onChange={e => setPassword(e.target.value)} placeholder='Digite sua senha' type={"password"} />
          </Form.Field>
          <Modal
            dimmer='blurring'
            trigger={<Button  primary className={styles.buttonPrimary} type={'submit'}>Entrar</Button>}
            header='Alerta'
            content={mensagem}
            actions={[{ key: 'done', content: 'OK', positive: true }]}
          />
        </Form> 
        </main>
         
    </div>
  )
}

